project:
  type: website

website:
  title: "Data Stories: Programming Journalism"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
format:
  html:
    theme: solar
    css: styles.css

execute:
  freeze: auto


