project:
  type: website

website:
  title: "Data Stories"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/sose27
     
format:
  html:
    theme: cyborg
    css: styles.css

execute:
  freeze: auto


